### ISSUE TITLE
zsh: occasionally seeing "command not found: complete" when loading subs

### ISSUE THREAD

**Issue by bradical** [qrush/sub#31]
I'm using:
- ITerm2(Build 1.0.0.20120203)
- zsh
- oh-my-zsh

and am sometimes seeing the following errors when opening new terminal windows or tabs:

```
/Users/bradley/Dropbox/bin/csd/libexec/../completions/csd.bash:14: command not found: complete
/Users/bradley/Dropbox/bin/sp/libexec/../completions/sp.bash:14: command not found: complete
/usr/local/Cellar/rbenv/0.3.0/libexec/../completions/rbenv.bash:14: command not found: complete
```

I'm assuming `rbenv` is also a sub so this is probably related.

The only thing I've noticed is that when my terminal profile is set to change into a particular directory on load, this tends to happen.

Here's the relevant portion of my `.zshrc` file:

```
... stuff before the end of the file ...
plugins=()

. ~/Dropbox/bin/z/z.sh
source ~/Dropbox/bin/ssh.bash
source ~/Dropbox/bin/mysql.bash
source ~/Dropbox/bin/du.bash

eval "$(/Users/bradley/Dropbox/bin/csd/bin/csd init -)"
eval "$(/Users/bradley/Dropbox/bin/sp/bin/sp init -)"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi # rbenv, ruby-build

source $ZSH/oh-my-zsh.sh
```

Any ideas?

**Comment by cweagans** [comment]
This should be reopened. `$SHELL` is only the default shell. It doesn't actually tell you with 100% certainty what the *current* shell is. Usually, they're they same, but if you run `zsh` as a subprocess of `bash` (for testing or whatever), you'll see this error. In my case, it was because iTerm was handling [this](http://take.ms/3ZN8E) option in a strange way - I think it was starting a bash shell, then running the command inside of a bash shell. `$SHELL`, then, was set to `/usr/local/bin/bash` in zsh. (I intend to switch my login shell to zsh, but for now, I'm using Terminal.app for day-to-day stuff while I get zsh configured. I can then test my config in iTerm, hence the odd setup).

The solution here is to harden the shell detection bits in `sub-init`. I suggest checking for `$BASH` and `$ZSH_NAME`. Those variables will be set on their respective shells
